markdown: kramdown
theme: null
permalink: /blog/:title:output_ext
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - updateRepos.js
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  style: compact # possible values: nested expanded compact compressed
collections:
  - repositories
name: Bruno Marques
username: Allakazan
userimg: https://avatars0.githubusercontent.com/u/25016389?v=4
meta: 
  title: Bruno Marques - Web Developer
  description: Welcome to the matrix. Full Stack Dev with experience in diverse technologies !
  image: https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1200&h=628&q=80